function userdata() {

    fulltree = new midnode("(Parasteatoda_tepidariorum{Common house spider},(Eurytemora_affinis{Calanoid copepod},((Ephemera_danica{Mayfly},Ladona_fulva{Scarce Chaser}:0)Palaeoptera,((((Anoplophora_glabripennis{Asian long-horned beetle},Leptinotarsa_decemlineata{Colorado potato beetle})Chrysomeloidea,Ceratitis_capitata{Mediterranean fruit fly}),((Orussus_abietinus{Parasitic Wood Wasp},Trichogramma_pretiosum{Parasitic wasp}),Athalia_rosae{Turnip sawfly})Hymenoptera)Endopterygota,(((Diaphorina_citri{Asian Citrus Psyllid},Pachypsylla_venusta{Hackberry petiole gall psyllid})Psyllidae,(Oncopeltus_fasciatus{Milkweed bug},Cimex_lectularius{Bed bug})Panheteroptera)Hemiptera,Frankliniella_occidentalis{Western flower thrips})Paraneoptera)Neoptera)Pterygota)Pancrustacea)Arthropoda;")}




//(((((((((((((((Ladona_fulva)Ladona)Libellulidae)Cavilabiata)Anisoptera)Anisoptera/Anisozygoptera_group)Odonata,(((((Ephemera_danica)Ephemera)Ephemeridae)Scapphodonta)Furcatergalia)Ephemeroptera)Palaeoptera,(((((((((((((((Ceratitis_capitata)Ceratitis)Ceratitis)Ceratitidini)Dacinae)Tephritidae)Tephritoidea)Acalyptratae)Schizophora)Cyclorrhapha)Eremoneura)Muscomorpha)Brachycera)Diptera,(((((Athalia_rosae)Athalia)Allantinae)Tenthredinidae)Tenthredinoidea,(((((Trichogramma_pretiosum)Trichogramma)Trichogrammatidae)Chalcidoidea)Chaldicoidea_group)Apocrita,(((Orussus_abietinus)Orussus)Orussidae)Orussoidea)Hymenoptera,((((((((Anoplophora_glabripennis)Anoplophora)Lamiini)Lamiinae)Cerambycidae,((((Leptinotarsa_decemlineata)Leptinotarsa)Doryphorini)Chrysomelinae)Chrysomelidae)Chrysomeloidea)Cucujiformia)Polyphaga)Coleoptera)Endopterygota,(((((((((((((Cimex_lectularius)Cimex)Cimicidae)Cimicoidea)Cimicomorpha,(((((Oncopeltus_fasciatus)Oncopeltus)Lygaeinae)Lygaeidae)Lygaeoidea)Pentatomomorpha)Panheteroptera)Neoheteroptera)Euheteroptera)Heteroptera)Prosorrhyncha)Neohemiptera)Euhemiptera,(((((Pachypsylla_venusta)Pachypsylla,(Diaphorina_citri)Diaphorina)Psyllidae)Psylloidea)Psylliformes)Sternorrhyncha)Hemiptera,((((((Frankliniella_occidentalis)Frankliniella)Thripinae)Thripidae)Thripoidea)Terebrantia)Thysanoptera)Paraneoptera)Neoptera)Pterygota)Dicondylia)Insecta)Hexapoda,((((((((Eurytemora_affinis)Eurytemora)Temoridae)Calanoida)Gymnoplea)Neocopepoda)Copepoda)Maxillopoda)Crustacea)Pancrustacea)Mandibulata,(((((((((Parasteatoda_tepidariorum)Parasteatoda)Theridiidae)Araneoidea)Orbiculariae)Entelegynae)Araneomorphae)Araneae)Arachnida)Chelicerata)Arthropoda);


//(Parasteatoda_tepidariorum{1}:0,(Eurytemora_affinis{2}:0,((Ephemera_danica{3}:0,Ladona_fulva{4}:0)Palaeoptera:0,(((Anoplophora_glabripennis{5}:0,Leptinotarsa_decemlineata{6}:0)Chrysomeloidea:0,Ceratitis_capitata{7}:0,(Orussus_abietinus{8}:0,Trichogramma_pretiosum{9}:0,Athalia_rosae{10}:0)Hymenoptera:0)Endopterygota:0,(((Diaphorina_citri{11}:0,Pachypsylla_venusta{12}:0)Psyllidae:0,(Oncopeltus_fasciatus{13}:0,Cimex_lectularius{14}:0)Panheteroptera:0)Hemiptera:0,Frankliniella_occidentalis{15}:0)Paraneoptera:0)Neoptera:0)Pterygota:0)Pancrustacea:0)Arthropoda:0;


//('Parasteatoda tepidariorum':4,('Eurytemora affinis':4,(('Ephemera danica':4,'Ladona fulva':4)Palaeoptera:4,(('Frankliniella occidentalis':4,(('Diaphorina citri':4,'Pachypsylla venusta':4)Psyllidae:4,('Cimex lectularius':4,'Oncopeltus fasciatus':4)Panheteroptera:4)Hemiptera:4)Paraneoptera:4,(('Anoplophora glabripennis':4,'Leptinotarsa decemlineata':4)Chrysomeloidea:4,('Orussus abietinus':4,'Athalia rosae':4,'Trichogramma pretiosum':4)Hymenoptera:4,'Ceratitis capitata':4)Endopterygota:4)Neoptera:4)Pterygota:4)Pancrustacea:4)Arthropoda:4;

